export enum InterestCategory {
  Technology = "Technology",
  Science = "Science",
  Arts = "Arts",
  Language = "Language",
  Meditation = "Meditation",
  Cooking = "Cooking",
  Finance = "Finance",
  Reading = "Reading",
  Sports = "Sports",
  Music = "Music",
  Travel = "Travel",
  Fashion = "Fashion",
  Gaming = "Gaming",
  Movies = "Movies",
  Fitness = "Fitness",
  Photography = "Photography",
  Education = "Education",
  Nature = "Nature",
  Pets = "Pets",
  DIY = "DIY",
  Writing = "Writing",
  Other = "Other",
}
