export enum CountryCode {
  US = 'us',
  CA = 'ca',
  UK = 'uk',
  AU = 'au',
  DE = 'de',
  FR = 'fr',
  JP = 'jp',
  IN = 'in',
  BR = 'br',
  ES = 'es',
  IT = 'it',
  NL = 'nl',
  SG = 'sg',
  KR = 'kr',
  MX = 'mx',
  ZA = 'za',
  SE = 'se',
  CN = 'cn',
  RU = 'ru',
  PT = 'pt',
  GR = 'gr',
  AE = 'ae',
}

export interface Country {
  id: CountryCode;
  name: string;
}

export const countries: Country[] = [
  { id: CountryCode.US, name: 'United States' },
  { id: CountryCode.CA, name: 'Canada' },
  { id: CountryCode.UK, name: 'United Kingdom' },
  { id: CountryCode.AU, name: 'Australia' },
  { id: CountryCode.DE, name: 'Germany' },
  { id: CountryCode.FR, name: 'France' },
  { id: CountryCode.JP, name: 'Japan' },
  { id: CountryCode.IN, name: 'India' },
  { id: CountryCode.BR, name: 'Brazil' },
  { id: CountryCode.ES, name: 'Spain' },
  { id: CountryCode.IT, name: 'Italy' },
  { id: CountryCode.NL, name: 'Netherlands' },
  { id: CountryCode.SG, name: 'Singapore' },
  { id: CountryCode.KR, name: 'South Korea' },
  { id: CountryCode.MX, name: 'Mexico' },
  { id: CountryCode.ZA, name: 'South Africa' },
  { id: CountryCode.SE, name: 'Sweden' },
  { id: CountryCode.CN, name: 'China' },
  { id: CountryCode.RU, name: 'Russia' },
  { id: CountryCode.PT, name: 'Portugal' },
  { id: CountryCode.GR, name: 'Greece' },
  { id: CountryCode.AE, name: 'United Arab Emirates' },
];

export const citiesByCountry: Record<CountryCode, string[]> = {
  [CountryCode.US]: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
  ],
  [CountryCode.CA]: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Kitchener',
  ],
  [CountryCode.UK]: [
    'London',
    'Birmingham',
    'Manchester',
    'Glasgow',
    'Liverpool',
    'Bristol',
    'Edinburgh',
    'Sheffield',
    'Leeds',
    'Newcastle',
  ],
  [CountryCode.AU]: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Wollongong',
    'Hobart',
  ],
  [CountryCode.DE]: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Leipzig',
    'Dortmund',
    'Essen',
  ],
  [CountryCode.FR]: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
  ],
  [CountryCode.JP]: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
  ],
  [CountryCode.IN]: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Lucknow',
  ],
  [CountryCode.BR]: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
  ],
  [CountryCode.ES]: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Bilbao',
    'Granada',
  ],
  [CountryCode.IT]: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Florence',
    'Venice',
    'Bologna',
    'Genoa',
    'Verona',
    'Palermo',
  ],
  [CountryCode.NL]: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
  ],
  [CountryCode.SG]: [
    'Marina Bay',
    'Orchard',
    'Jurong East',
    'Tampines',
    'Woodlands',
    'Punggol',
    'Ang Mo Kio',
    'Clementi',
    'Bedok',
    'Yishun',
  ],
  [CountryCode.KR]: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Ulsan',
    'Seongnam',
    'Goyang',
  ],
  [CountryCode.MX]: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Cancún',
    'Mérida',
    'Querétaro',
  ],
  [CountryCode.ZA]: [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
    'Nelspruit',
    'Kimberley',
    'Polokwane',
  ],
  [CountryCode.SE]: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Jönköping',
    'Norrköping',
  ],
  [CountryCode.CN]: [
    'Shanghai',
    'Beijing',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Wuhan',
    "Xi'an",
    'Tianjin',
    'Chongqing',
  ],
  [CountryCode.RU]: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
    'Samara',
    'Omsk',
    'Rostov-on-Don',
    'Chelyabinsk',
  ],
  [CountryCode.PT]: [
    'Lisbon',
    'Porto',
    'Braga',
    'Coimbra',
    'Funchal',
    'Aveiro',
    'Faro',
    'Évora',
    'Guimarães',
    'Setúbal',
  ],
  [CountryCode.GR]: [
    'Athens',
    'Thessaloniki',
    'Patras',
    'Heraklion',
    'Larissa',
    'Volos',
    'Rhodes',
    'Ioannina',
    'Chania',
    'Kavala',
  ],
  [CountryCode.AE]: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Al Ain',
    'Fujairah',
    'Umm Al Quwain',
    'Dubai Marina',
    'Palm Jumeirah',
  ],
};
