export enum InterestCategory {
  Technology = 'Technology',
  Science = 'Science',
  Arts = 'Arts',
  Sports = 'Sports',
  Music = 'Music',
  Travel = 'Travel',
  FoodAndCooking = 'Food & Cooking',
  Fashion = 'Fashion',
  Gaming = 'Gaming',
  Books = 'Books',
  Movies = 'Movies',
  Fitness = 'Fitness',
  Photography = 'Photography',
  Education = 'Education',
  Business = 'Business',
  Nature = 'Nature',
  Pets = 'Pets',
  DIY = 'DIY',
  Writing = 'Writing',
  Other = 'Other',
}

export const CommoditiesByCategory: Record<InterestCategory, string[]> = {
  [InterestCategory.Technology]: [
    'Web Development',
    'Mobile Apps',
    'AI/ML',
    'Cybersecurity',
    'Cloud Computing',
    'Blockchain',
    'IoT',
    'Data Science',
    'DevOps',
    'UI/UX Design',
  ],
  [InterestCategory.Science]: [
    'Physics',
    'Chemistry',
    'Biology',
    'Astronomy',
    'Mathematics',
    'Environmental Science',
    'Neuroscience',
    'Genetics',
    'Quantum Computing',
    'Robotics',
  ],
  [InterestCategory.Arts]: [
    'Painting',
    'Sculpting',
    'Drawing',
    'Digital Art',
    'Pottery',
    'Printmaking',
    'Art History',
    'Contemporary Art',
    'Street Art',
    'Animation',
  ],
  [InterestCategory.Sports]: [
    'Football',
    'Basketball',
    'Tennis',
    'Golf',
    'Soccer',
    'Baseball',
    'Swimming',
    'Martial Arts',
    'Cycling',
    'Rock Climbing',
  ],
  [InterestCategory.Music]: ['Rock', 'Pop', 'Jazz', 'Classical', 'Hip-Hop'],
  [InterestCategory.Travel]: [
    'Europe',
    'Asia',
    'Africa',
    'North America',
    'South America',
  ],
  [InterestCategory.FoodAndCooking]: [
    'Italian Cuisine',
    'Asian Cuisine',
    'Baking',
    'Vegetarian/Vegan',
    'Wine & Spirits',
    'Restaurant Reviews',
    'Food Photography',
    'Meal Planning',
    'Sustainable Food',
    'Food Science',
  ],
  [InterestCategory.Fashion]: [
    'Streetwear',
    'High Fashion',
    'Vintage',
    'Sustainable Fashion',
    'Boutique Fashion',
  ],
  [InterestCategory.Gaming]: [
    'Video Games',
    'Board Games',
    'Card Games',
    'Role-Playing Games',
    'Strategy Games',
  ],
  [InterestCategory.Books]: [
    'Fiction',
    'Non-Fiction',
    'Biographies',
    'Fantasy',
    'Science Fiction',
  ],
  [InterestCategory.Movies]: [
    'Action',
    'Adventure',
    'Comedy',
    'Drama',
    'Horror',
  ],
  [InterestCategory.Fitness]: [
    'Yoga',
    'Pilates',
    'CrossFit',
    'Weight Training',
    'HIIT',
    'Running',
    'Calisthenics',
    'Personal Training',
    'Nutrition',
    'Mental Wellness',
  ],
  [InterestCategory.Photography]: [
    'Landscape',
    'Portrait',
    'Street',
    'Wildlife',
    'Macro',
  ],
  [InterestCategory.Education]: [
    'Online Courses',
    'Tutoring',
    'Workshops',
    'Seminars',
    'Webinars',
  ],
  [InterestCategory.Business]: [
    'Entrepreneurship',
    'Marketing',
    'Sales',
    'Finance',
    'Investment',
    'Project Management',
    'Business Strategy',
    'E-commerce',
    'Startups',
    'Business Analytics',
  ],
  [InterestCategory.Nature]: [
    'Hiking',
    'Camping',
    'Gardening',
    'Wildlife',
    'Birdwatching',
  ],
  [InterestCategory.Pets]: ['Dogs', 'Cats', 'Birds', 'Fish', 'Reptiles'],
  [InterestCategory.DIY]: [
    'Home Improvement',
    'DIY Crafts',
    'DIY Electronics',
    'DIY Furniture',
    'DIY Gardening',
  ],
  [InterestCategory.Writing]: [
    'Creative Writing',
    'Technical Writing',
    'Copywriting',
    'Blog Writing',
    'Freelance Writing',
  ],
  [InterestCategory.Other]: [
    'Miscellaneous',
    'General Interest',
    'Other Activities',
  ],
};

export type InterestCategoryType = keyof typeof InterestCategory;
export type CommodityType =
  (typeof CommoditiesByCategory)[InterestCategory][number];

export const isCommodityInCategory = (
  category: InterestCategory,
  commodity: string,
): boolean => {
  return CommoditiesByCategory[category].includes(commodity);
};
