export enum Categories {
  Fitness = 'Fitness',
  PersonalGrowth = 'Personal Growth',
  Lifestyle = 'Lifestyle',
  Technology = 'Technology',
  ArtsAndCulture = 'Arts & Culture',
  OutdoorActivities = 'Outdoor Activities',
}

export enum Interests {
  // Fitness
  Running = 'Running',
  Yoga = 'Yoga',
  WeightTraining = 'Weight Training',
  Cycling = 'Cycling',
  Swimming = 'Swimming',
  HIIT = 'HIIT',
  Pilates = 'Pilates',
  Tennis = 'Tennis',
  CrossFit = 'CrossFit',
  RockClimbing = 'Rock Climbing',
  MartialArts = 'Martial Arts',
  Dance = 'Dance',
  Basketball = 'Basketball',
  Soccer = 'Soccer',

  // Personal Growth
  Reading = 'Reading',
  Meditation = 'Meditation',
  Journaling = 'Journaling',
  LearningLanguages = 'Learning Languages',
  Coding = 'Coding',
  Art = 'Art',
  Music = 'Music',
  PublicSpeaking = 'Public Speaking',
  PersonalFinance = 'Personal Finance',
  Leadership = 'Leadership',
  TimeManagement = 'Time Management',
  CreativeWriting = 'Creative Writing',
  Philosophy = 'Philosophy',
  SelfDevelopment = 'Self-Development',

  // Lifestyle
  Cooking = 'Cooking',
  Gardening = 'Gardening',
  Photography = 'Photography',
  Travel = 'Travel',
  Fashion = 'Fashion',
  DIYProjects = 'DIY Projects',
  Volunteering = 'Volunteering',
  BoardGames = 'Board Games',
  InteriorDesign = 'Interior Design',
  WineTasting = 'Wine Tasting',
  CoffeeCulture = 'Coffee Culture',
  SustainableLiving = 'Sustainable Living',
  PetCare = 'Pet Care',
  HomeOrganization = 'Home Organization',

  // Technology
  WebDevelopment = 'Web Development',
  MobileApps = 'Mobile Apps',
  ArtificialIntelligence = 'Artificial Intelligence',
  Blockchain = 'Blockchain',
  Cybersecurity = 'Cybersecurity',
  DataScience = 'Data Science',
  Gaming = 'Gaming',
  VirtualReality = 'Virtual Reality',
  ThreeDPrinting = '3D Printing',
  SmartHome = 'Smart Home',

  // Arts & Culture
  Painting = 'Painting',
  Drawing = 'Drawing',
  Sculpture = 'Sculpture',
  FilmAndCinema = 'Film & Cinema',
  Theater = 'Theater',
  Literature = 'Literature',
  Poetry = 'Poetry',
  Museums = 'Museums',
  CulturalEvents = 'Cultural Events',
  StreetArt = 'Street Art',

  // Outdoor Activities
  Hiking = 'Hiking',
  Camping = 'Camping',
  BirdWatching = 'Bird Watching',
  MountainBiking = 'Mountain Biking',
  Kayaking = 'Kayaking',
  Fishing = 'Fishing',
  Skiing = 'Skiing',
  Surfing = 'Surfing',
  NaturePhotography = 'Nature Photography',
  Stargazing = 'Stargazing',
}

// Helper type to map categories to their interests
export const CATEGORY_INTERESTS: Record<Categories, Interests[]> = {
  [Categories.Fitness]: [
    Interests.Running,
    Interests.Yoga,
    Interests.WeightTraining,
    Interests.Cycling,
    Interests.Swimming,
    Interests.HIIT,
    Interests.Pilates,
    Interests.Tennis,
    Interests.CrossFit,
    Interests.RockClimbing,
    Interests.MartialArts,
    Interests.Dance,
    Interests.Basketball,
    Interests.Soccer,
  ],
  [Categories.PersonalGrowth]: [
    Interests.Reading,
    Interests.Meditation,
    Interests.Journaling,
    Interests.LearningLanguages,
    Interests.Coding,
    Interests.Art,
    Interests.Music,
    Interests.PublicSpeaking,
    Interests.PersonalFinance,
    Interests.Leadership,
    Interests.TimeManagement,
    Interests.CreativeWriting,
    Interests.Philosophy,
    Interests.SelfDevelopment,
  ],
  [Categories.Lifestyle]: [
    Interests.Cooking,
    Interests.Gardening,
    Interests.Photography,
    Interests.Travel,
    Interests.Fashion,
    Interests.DIYProjects,
    Interests.Volunteering,
    Interests.BoardGames,
    Interests.InteriorDesign,
    Interests.WineTasting,
    Interests.CoffeeCulture,
    Interests.SustainableLiving,
    Interests.PetCare,
    Interests.HomeOrganization,
  ],
  [Categories.Technology]: [
    Interests.WebDevelopment,
    Interests.MobileApps,
    Interests.ArtificialIntelligence,
    Interests.Blockchain,
    Interests.Cybersecurity,
    Interests.DataScience,
    Interests.Gaming,
    Interests.VirtualReality,
    Interests.ThreeDPrinting,
    Interests.SmartHome,
  ],
  [Categories.ArtsAndCulture]: [
    Interests.Painting,
    Interests.Drawing,
    Interests.Sculpture,
    Interests.FilmAndCinema,
    Interests.Theater,
    Interests.Literature,
    Interests.Poetry,
    Interests.Museums,
    Interests.CulturalEvents,
    Interests.StreetArt,
  ],
  [Categories.OutdoorActivities]: [
    Interests.Hiking,
    Interests.Camping,
    Interests.BirdWatching,
    Interests.MountainBiking,
    Interests.Kayaking,
    Interests.Fishing,
    Interests.Skiing,
    Interests.Surfing,
    Interests.NaturePhotography,
    Interests.Stargazing,
  ],
};
