export enum InterestCategory {
  TECHNOLOGY = 'Technology',
  SCIENCE = 'Science',
  ARTS = 'Arts',
  SPORTS = 'Sports',
  MUSIC = 'Music',
  TRAVEL = 'Travel',
  FOOD_AND_COOKING = 'Food & Cooking',
  FASHION = 'Fashion',
  GAMING = 'Gaming',
  BOOKS = 'Books',
  MOVIES = 'Movies',
  FITNESS = 'Fitness',
  PHOTOGRAPHY = 'Photography',
  EDUCATION = 'Education',
  BUSINESS = 'Business',
  NATURE = 'Nature',
  PETS = 'Pets',
  DIY = 'DIY',
  WRITING = 'Writing',
}

export const CommoditiesByCategory: Record<InterestCategory, string[]> = {
  [InterestCategory.TECHNOLOGY]: [
    'Web Development',
    'Mobile Apps',
    'AI/ML',
    'Cybersecurity',
    'Cloud Computing',
    'Blockchain',
    'IoT',
    'Data Science',
    'DevOps',
    'UI/UX Design',
  ],
  [InterestCategory.SCIENCE]: [
    'Physics',
    'Chemistry',
    'Biology',
    'Astronomy',
    'Mathematics',
    'Environmental Science',
    'Neuroscience',
    'Genetics',
    'Quantum Computing',
    'Robotics',
  ],
  [InterestCategory.ARTS]: [
    'Painting',
    'Sculpting',
    'Drawing',
    'Digital Art',
    'Pottery',
    'Printmaking',
    'Art History',
    'Contemporary Art',
    'Street Art',
    'Animation',
  ],
  [InterestCategory.SPORTS]: [
    'Football',
    'Basketball',
    'Tennis',
    'Golf',
    'Soccer',
    'Baseball',
    'Swimming',
    'Martial Arts',
    'Cycling',
    'Rock Climbing',
  ],
  [InterestCategory.MUSIC]: ['Rock', 'Pop', 'Jazz', 'Classical', 'Hip-Hop'],
  [InterestCategory.TRAVEL]: [
    'Europe',
    'Asia',
    'Africa',
    'North America',
    'South America',
  ],
  [InterestCategory.FOOD_AND_COOKING]: [
    'Italian Cuisine',
    'Asian Cuisine',
    'Baking',
    'Vegetarian/Vegan',
    'Wine & Spirits',
    'Restaurant Reviews',
    'Food Photography',
    'Meal Planning',
    'Sustainable Food',
    'Food Science',
  ],
  [InterestCategory.FASHION]: [
    'Streetwear',
    'High Fashion',
    'Vintage',
    'Sustainable Fashion',
    'Boutique Fashion',
  ],
  [InterestCategory.GAMING]: [
    'Video Games',
    'Board Games',
    'Card Games',
    'Role-Playing Games',
    'Strategy Games',
  ],
  [InterestCategory.BOOKS]: [
    'Fiction',
    'Non-Fiction',
    'Biographies',
    'Fantasy',
    'Science Fiction',
  ],
  [InterestCategory.MOVIES]: [
    'Action',
    'Adventure',
    'Comedy',
    'Drama',
    'Horror',
  ],
  [InterestCategory.FITNESS]: [
    'Yoga',
    'Pilates',
    'CrossFit',
    'Weight Training',
    'HIIT',
    'Running',
    'Calisthenics',
    'Personal Training',
    'Nutrition',
    'Mental Wellness',
  ],
  [InterestCategory.PHOTOGRAPHY]: [
    'Landscape',
    'Portrait',
    'Street',
    'Wildlife',
    'Macro',
  ],
  [InterestCategory.EDUCATION]: [
    'Online Courses',
    'Tutoring',
    'Workshops',
    'Seminars',
    'Webinars',
  ],
  [InterestCategory.BUSINESS]: [
    'Entrepreneurship',
    'Marketing',
    'Sales',
    'Finance',
    'Investment',
    'Project Management',
    'Business Strategy',
    'E-commerce',
    'Startups',
    'Business Analytics',
  ],
  [InterestCategory.NATURE]: [
    'Hiking',
    'Camping',
    'Gardening',
    'Wildlife',
    'Birdwatching',
  ],
  [InterestCategory.PETS]: ['Dogs', 'Cats', 'Birds', 'Fish', 'Reptiles'],
  [InterestCategory.DIY]: [
    'Home Improvement',
    'DIY Crafts',
    'DIY Electronics',
    'DIY Furniture',
    'DIY Gardening',
  ],
  [InterestCategory.WRITING]: [
    'Creative Writing',
    'Technical Writing',
    'Copywriting',
    'Blog Writing',
    'Freelance Writing',
  ],
};

export type InterestCategoryType = keyof typeof InterestCategory;
export type CommodityType =
  (typeof CommoditiesByCategory)[InterestCategory][number];

export const isCommodityInCategory = (
  category: InterestCategory,
  commodity: string,
): boolean => {
  return CommoditiesByCategory[category].includes(commodity);
};
