export enum UserInterest {
  TECHNOLOGY = 'Technology',
  SCIENCE = 'Science',
  ARTS = 'Arts',
  SPORTS = 'Sports',
  MUSIC = 'Music',
  TRAVEL = 'Travel',
  FOOD = 'Food',
  FASHION = 'Fashion',
  GAMING = 'Gaming',
  BOOKS = 'Books',
  MOVIES = 'Movies',
  FITNESS = 'Fitness',
  PHOTOGRAPHY = 'Photography',
  EDUCATION = 'Education',
  BUSINESS = 'Business',
  NATURE = 'Nature',
  PETS = 'Pets',
  COOKING = 'Cooking',
  DIY = 'DIY',
  WRITING = 'Writing',
}

export enum Country {
  USA = 'United States',
  UK = 'United Kingdom',
  CANADA = 'Canada',
  AUSTRALIA = 'Australia',
  GERMANY = 'Germany',
  FRANCE = 'France',
  ITALY = 'Italy',
  SPAIN = 'Spain',
  JAPAN = 'Japan',
  CHINA = 'China',
  INDIA = 'India',
  BRAZIL = 'Brazil',
  MEXICO = 'Mexico',
  NETHERLANDS = 'Netherlands',
  SWEDEN = 'Sweden',
  NORWAY = 'Norway',
  DENMARK = 'Denmark',
  SINGAPORE = 'Singapore',
  UAE = 'United Arab Emirates',
  SOUTH_KOREA = 'South Korea',
}

// city mappings per country
export const CitiesByCountry: Record<Country, string[]> = {
  [Country.USA]: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'San Francisco',
    'Columbus',
    'Fort Worth',
    'Indianapolis',
    'Charlotte',
    'Seattle',
    'Denver',
    'Boston',
  ],
  [Country.UK]: [
    'London',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Leeds',
    'Glasgow',
    'Sheffield',
    'Edinburgh',
    'Bristol',
    'Cardiff',
    'Newcastle',
    'Nottingham',
    'Belfast',
    'Leicester',
    'Brighton',
  ],
  [Country.CANADA]: [
    'Toronto',
    'Vancouver',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Quebec City',
    'Winnipeg',
    'Halifax',
    'Victoria',
    'Hamilton',
    'London',
    'Regina',
    "St. John's",
    'Saskatoon',
  ],
  [Country.AUSTRALIA]: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Wollongong',
    'Logan City',
    'Hobart',
    'Townsville',
    'Darwin',
    'Cairns',
    'Geelong',
  ],
  [Country.GERMANY]: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Leipzig',
    'Dortmund',
    'Essen',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
  ],
  [Country.FRANCE]: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Saint-Étienne',
    'Toulon',
    'Grenoble',
  ],
  [Country.ITALY]: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Venice',
    'Verona',
    'Bari',
    'Catania',
    'Padua',
    'Trieste',
    'Brescia',
  ],
  [Country.SPAIN]: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
    'Granada',
  ],
  [Country.JAPAN]: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Chiba',
    'Kitakyushu',
    'Sakai',
  ],
  [Country.CHINA]: [
    'Shanghai',
    'Beijing',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Tianjin',
    'Wuhan',
    'Dongguan',
    'Chongqing',
    'Nanjing',
    'Hangzhou',
    'Foshan',
    'Shenyang',
    "Xi'an",
    'Suzhou',
  ],
  [Country.INDIA]: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Surat',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
  ],
  [Country.BRAZIL]: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'São Luís',
  ],
  [Country.MEXICO]: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Zapopan',
    'Mérida',
    'San Luis Potosí',
    'Querétaro',
    'Aguascalientes',
    'Morelia',
    'Hermosillo',
    'Saltillo',
  ],
  [Country.NETHERLANDS]: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
    'Enschede',
    'Haarlem',
    'Arnhem',
    'Zaanstad',
    'Amersfoort',
  ],
  [Country.SWEDEN]: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Jönköping',
    'Norrköping',
    'Lund',
    'Umeå',
    'Gävle',
    'Borås',
    'Södertälje',
  ],
  [Country.NORWAY]: [
    'Oslo',
    'Bergen',
    'Trondheim',
    'Stavanger',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Sandnes',
    'Tromsø',
    'Sarpsborg',
    'Skien',
    'Ålesund',
    'Sandefjord',
    'Haugesund',
    'Tønsberg',
  ],
  [Country.DENMARK]: [
    'Copenhagen',
    'Aarhus',
    'Odense',
    'Aalborg',
    'Frederiksberg',
    'Esbjerg',
    'Randers',
    'Kolding',
    'Horsens',
    'Vejle',
    'Roskilde',
    'Herning',
    'Silkeborg',
    'Næstved',
    'Fredericia',
  ],
  [Country.SINGAPORE]: [
    'Singapore', // City-state
  ],
  [Country.UAE]: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Al Ain',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
    'Dubai World Central',
    'Dibba Al-Fujairah',
    'Madinat Zayed',
    'Ruwais',
    'Liwa Oasis',
    'Ghayathi',
    'Delma',
  ],
  [Country.SOUTH_KOREA]: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Ulsan',
    'Seongnam',
    'Goyang',
    'Bucheon',
    'Cheongju',
    'Ansan',
    'Anyang',
    'Changwon',
  ],
};
