export const countries = [
  { id: "us", name: "United States" },
  { id: "ca", name: "Canada" },
  { id: "uk", name: "United Kingdom" },
  { id: "au", name: "Australia" },
  { id: "de", name: "Germany" },
  { id: "fr", name: "France" },
  { id: "jp", name: "Japan" },
  { id: "in", name: "India" },
  { id: "br", name: "Brazil" },
  { id: "es", name: "Spain" },
  { id: "it", name: "Italy" },
  { id: "nl", name: "Netherlands" },
  { id: "sg", name: "Singapore" },
  { id: "kr", name: "South Korea" },
  { id: "mx", name: "Mexico" },
  { id: "za", name: "South Africa" },
  { id: "se", name: "Sweden" },
  { id: "cn", name: "China" },
  { id: "ru", name: "Russia" },
  { id: "pt", name: "Portugal" },
  { id: "gr", name: "Greece" },
  { id: "ae", name: "United Arab Emirates" },
];

export const citiesByCountry = {
  us: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
  ],
  ca: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
  ],
  uk: [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Liverpool",
    "Bristol",
    "Edinburgh",
    "Sheffield",
    "Leeds",
    "Newcastle",
  ],
  au: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Wollongong",
    "Hobart",
  ],
  de: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
  ],
  fr: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
  ],
  jp: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
  ],
  in: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
  ],
  br: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
  ],
  es: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Bilbao",
    "Granada",
  ],
  it: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Florence",
    "Venice",
    "Bologna",
    "Genoa",
    "Verona",
    "Palermo",
  ],
  nl: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
  ],
  sg: [
    "Marina Bay",
    "Orchard",
    "Jurong East",
    "Tampines",
    "Woodlands",
    "Punggol",
    "Ang Mo Kio",
    "Clementi",
    "Bedok",
    "Yishun",
  ],
  kr: [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Seongnam",
    "Goyang",
  ],
  mx: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Cancún",
    "Mérida",
    "Querétaro",
  ],
  za: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Nelspruit",
    "Kimberley",
    "Polokwane",
  ],
  se: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
  ],
  cn: [
    "Shanghai",
    "Beijing",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hangzhou",
    "Wuhan",
    "Xi'an",
    "Tianjin",
    "Chongqing",
  ],
  ru: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Chelyabinsk",
  ],
  pt: [
    "Lisbon",
    "Porto",
    "Braga",
    "Coimbra",
    "Funchal",
    "Aveiro",
    "Faro",
    "Évora",
    "Guimarães",
    "Setúbal",
  ],
  gr: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Rhodes",
    "Ioannina",
    "Chania",
    "Kavala",
  ],
  ae: [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Al Ain",
    "Fujairah",
    "Umm Al Quwain",
    "Dubai Marina",
    "Palm Jumeirah",
  ],
};
