// Predefined interests
export const interestCategories = [
  {
    name: "Fitness",
    options: [
      "Running",
      "Yoga",
      "Weight Training",
      "Cycling",
      "Swimming",
      "HIIT",
      "Pilates",
      "Tennis",
      "CrossFit",
      "Rock Climbing",
      "Martial Arts",
      "Dance",
      "Basketball",
      "Soccer",
    ],
  },
  {
    name: "Personal Growth",
    options: [
      "Reading",
      "Meditation",
      "Journaling",
      "Learning Languages",
      "Coding",
      "Art",
      "Music",
      "Public Speaking",
      "Personal Finance",
      "Leadership",
      "Time Management",
      "Creative Writing",
      "Philosophy",
      "Self-Development",
    ],
  },
  {
    name: "Lifestyle",
    options: [
      "Cooking",
      "Gardening",
      "Photography",
      "Travel",
      "Fashion",
      "DIY Projects",
      "Volunteering",
      "Board Games",
      "Interior Design",
      "Wine Tasting",
      "Coffee Culture",
      "Sustainable Living",
      "Pet Care",
      "Home Organization",
    ],
  },
  {
    name: "Technology",
    options: [
      "Web Development",
      "Mobile Apps",
      "Artificial Intelligence",
      "Blockchain",
      "Cybersecurity",
      "Data Science",
      "Gaming",
      "Virtual Reality",
      "3D Printing",
      "Smart Home",
    ],
  },
  {
    name: "Arts & Culture",
    options: [
      "Painting",
      "Drawing",
      "Sculpture",
      "Film & Cinema",
      "Theater",
      "Literature",
      "Poetry",
      "Museums",
      "Cultural Events",
      "Street Art",
    ],
  },
  {
    name: "Outdoor Activities",
    options: [
      "Hiking",
      "Camping",
      "Bird Watching",
      "Mountain Biking",
      "Kayaking",
      "Fishing",
      "Skiing",
      "Surfing",
      "Nature Photography",
      "Stargazing",
    ],
  },
];
